# GABRIEL Document Analysis Tutorial

This notebook demonstrates how to use GABRIEL to analyze text documents.

## Prerequisites

Set environment variables for Azure OpenAI:
```bash
export AZURE_OPENAI_API_KEY="your-api-key"
export AZURE_OPENAI_ENDPOINT="https://your-endpoint.openai.azure.com/"
```

## Step 1: Setup and Imports

In [ ]:
import os
import sys
import pandas as pd

# Add src to path if running from examples directory
sys.path.insert(0, os.path.abspath('../src'))

import gabriel

os.environ["AZURE_OPENAI_API_KEY"] = "THE_KEY"
os.environ["AZURE_OPENAI_ENDPOINT"] = "THE_ENDPOINT"

## Step 2: Load the Markdown Document

In [2]:
# Load the markdown file
doc_path = "2025-11-21 MR AGO.md"

with open(doc_path, "r", encoding="utf-8") as f:
    content = f.read()

print(f"Document length: {len(content)} characters")
print("\n--- Preview (first 1500 chars) ---\n")
print(content[:1500])

Document length: 13325 characters

--- Preview (first 1500 chars) ---

 **To:** 	Dr. Sheetal Singh
**From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
**Subject:** Week 12 Management Report – Week Ending December 11, 2025
**Copies:** Instructor Team

**Key indicators**

|  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
| :---- | :---: | :---: | :---: | :---: | :---: | :---: |
| Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

| *Tasks* |  |  |  |  |
| ----- | :---: | ----- | ----- | :---: |
| **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
| Find Website Host | All | 9/25 | 10/3 | N/A |
| Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
| Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
| Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
| Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
| Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
| Experimentation and Learning |   | 9/30 | 9/30 |  |
| Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
| Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
| Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
| Make a MVP | All | 10/13 | 10/16 | 10/16 |
| Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
| Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
| Go to marketplaces and talk to customers and ven

## Step 3: Prepare DataFrame

GABRIEL works with pandas DataFrames. Each row represents one unit of analysis.

In [3]:
# Create DataFrame with document content
df = pd.DataFrame({
    "doc_id": ["MR_AGO_Week12"],
    "content": [content]
})

# Create output directory
output_dir = "mr_analysis_output"
os.makedirs(output_dir, exist_ok=True)

df

          doc_id                                            content
0  MR_AGO_Week12   **To:** \tDr. Sheetal Singh    \n**From:** Te...

## Example A: Extract Structured Information

`gabriel.extract()` pulls out specific facts from text as string/numeric values.

In [ ]:
# Extract key information from the management report
extracted = await gabriel.extract(
    df=df,
    column_name="content",
    attributes={
        "team_name": "What is the team name?",
        "team_members": "List all team member names, separated by commas",
        "report_week": "What week is this report for?",
    },
    save_dir=f"{output_dir}/extraction",
    model="gpt-5.2",
)

# Display results vertically for readability
for col in extracted.columns:
    if col != "content":
        print(f"{col}: {extracted[col].iloc[0]}")

[Extract] Rendering 1 prompts…

2026-01-14 22:35:07,667 - gabriel.utils.openai_utils - WARNING - ⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

Initializing model calls and loading data...

===== Run kickoff =====
Prompts: 1 | Words: ~6,138 | Words per prompt: ~6,138
Model: gpt-5.2 | Mode: streaming
Pricing for model 'gpt-5.2': input $1.75/1M, output $14.0/1M
Estimated token usage: input 9,207, output 500 | ~10,207 tokens per call
Estimated synchronous cost: $0.02 (input: $0.02, output: $0.01)

===== Run limits =====
Requests per minute: unknown (API did not share a request limit)
Tokens per minute: unknown (API did not share a token limit)
Approx. words per minute: unknown
We can run up to 650 requests at the same time with your current settings.
⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

===== Example prompt =====
  Entity:  **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |
  | All12/5 | Launched Google Form survey to gather quantitative data on shopping habits. |
  | All12/5 | Executed usability testing with 10 students to refine design and flow. |
  | All12/8 | Developed and finalized the MVP (Minimum Viable Product). |
  | All12/4 | Created wireframes (Homepage, Upload, Product Listing) for internal feedback.  |
  | All12/9 | Drafted comprehensive Terms of Service (Customer & Business) and Partnership Agreements. |
  | All12/10 | Finalized Team Contract and Project Pitch presentation. |

  During the next week, we plan to finish these tasks:

  | Who | What |
  | ----- | :---- |
  | All  | Create and link official Agora Instagram and TikTok accounts; start posting teaser content and spotlighting student businesses. |
  | All  | Initialize social channels (IG/TikTok) |
  | All 12/8 | Deploy teaser content strategy |
  | All 12/8 | Launch "Vendor Spotlight" series |
  | All12/9 | Submit "First Sale" deliverable |
  | All12/9  | Finalize legal compliance review |
  | All12/11 | Complete investment pitch deck |
  | All12/11 | Recalibrate business valuation |



  **Problems**

  We are aware of these problems:

  | Owner   (Due Date) | What |
  | ----- | :---- |
  | All | Our initial financial modeling relied on optimistic growth assumptions, resulting in an inflated valuation that required significant recalibration to align with realistic market comparables. |
  | All | The pilot phase highlighted that the current bootstrap model is insufficient; lack of immediate liquidity posed a challenge for aggressive marketing and scaling operations. |
  | All | We encountered high friction during the initial outreach phase, as the lack of established market history made it difficult to negotiate favorable payment terms with vendor partners. |
  | All | Ensuring the product's viability required pushing the website builder’s CMS to its absolute technical limits, which created unforeseen design and functionality constraints. |
  | All | Delays in fully integrating the Stripe API created a temporary bottleneck for seamless transaction processing and revenue capture. |
  | AllAll | Overcoming the "cold start" problem was difficult, specifically regarding the lack of a centralized infrastructure to communicate with and mobilize the brand ambassador network. |
  | All | N/A |
  | All | N/A |

  **Priorities**

  We are working on these priorities:

  1. Continue customer discover, expand focus to sellers as well
  2. Create a financial business plan, figuring out revenue model
  3. Change logo and better our branding


  ## Attachments

  [**INTERVIEW Q’S**](https://docs.google.com/document/d/1-WRxkrk7u6Cw6d2Wa6BB266PzQ-Ilj-7jjJojB1Brxw/edit?usp=sharing)

  [**NOTES**](https://docs.google.com/document/d/1yBBKoNJMZe0GdEP_d6TxdEGd-Dl6UVV7JEjRLCLkUQ8/edit?usp=sharing)

   **[TEAM CONTRACT](https://docs.google.com/document/d/1XSt8-kGiMDpUR67xrhzCb7M-xrWSmZPYBfSFvIvtiak/edit?usp=sharing) \- Handled by Balraj**

  [**AGORA Financial Statements**](https://umd0-my.sharepoint.com/:x:/g/personal/kdillow_umd_edu/EVTzXjCt8W9CqHPiMy3lG2ABiCsC_mqWRKEEjxzqKGVT5g?e=47zBvo)

  [**https://termly.io/products/tl/terms-of-service/?utm\_campaign\_id=863370649\&utm\_adgroup=\&utm\_adgroup\_id=118961433494\&utm\_source=google\&utm\_medium=cpc\&utm\_campaign=terms\_and\_conditions\_us\&utm\_term=terms%20of%20service%20generator%20free\&utm\_content=575886964693\&hsa\_acc=8931548921\&hsa\_cam=863370649\&hsa\_grp=118961433494\&hsa\_ad=575886964693\&hsa\_src=g\&hsa\_tgt=kwd-45051882079\&hsa\_kw=terms%20of%20service%20generator%20free\&hsa\_mt=e\&hsa\_net=adwords\&hsa\_ver=3\&gad\_source=1\&gad\_campaignid=863370649\&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI\&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9\_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw\_wcB**](https://termly.io/products/tl/terms-of-service/?utm_campaign_id=863370649&utm_adgroup=&utm_adgroup_id=118961433494&utm_source=google&utm_medium=cpc&utm_campaign=terms_and_conditions_us&utm_term=terms%20of%20service%20generator%20free&utm_content=575886964693&hsa_acc=8931548921&hsa_cam=863370649&hsa_grp=118961433494&hsa_ad=575886964693&hsa_src=g&hsa_tgt=kwd-45051882079&hsa_kw=terms%20of%20service%20generator%20free&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=863370649&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw_wcB)

  **[Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/17Ap9n2uROK2MwPNprxZ4sx-DrIFNlv8h5ijYyUeE2tM/edit?usp=drivesdk)**

  **[Copy of Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/1sDcC0_Cmw3CJ7RW3_mya2sZ84Q6xB__6wux7SQoI4YE/edit?usp=drivesdk)**

  [**https://docs.google.com/document/d/1-ZpfHAWhvp\_Yk\_qWcQ5SeT6Hf\_BkBuVeeNrRYqypsj4/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1-ZpfHAWhvp_Yk_qWcQ5SeT6Hf_BkBuVeeNrRYqypsj4/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\- Luke Interview 1**

  [**https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\-  Luke Interview 2**

  [**https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing**](https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing)

  **SORA PROMPT**

  **Duration: 30 seconds. Aspect ratio 16:9.**
  **Begin with a wide aerial sweeping drone shot of an ancient open-air Greek marketplace at golden hour lighting: stone paved lanes, wooden stalls under white linen awnings, gentle sunlight casting long warm shadows, bright terracotta and cream tones. The scene is lively: buyers browsing, artisans showcasing handcrafted goods. Camera slowly dolly-in and pan across the stalls.**
  **Cut to a medium close-up of a vendor (modern and friendly) behind a stall laden with handcrafted jewelry, vintage furniture pieces, artisan food jars. The vendor smiles and taps on a sleek tablet labelled “Agora-Market.com”. The buyer across taps “Connect” on the tablet. Subtle digital overlay appears: category filters on screen.**
  **Transition via a digital wipe/whip-pan into a modern browser/mobile UI of Agora-Market.com: a clean minimal interface, categories “Handmade”, “Vintage”, “Locally Sourced Food”, colourful icons, a chat icon. Show a buyer scrolling, filtering, clicking “Message Seller” then “Purchase/Exchange”. Use a subtle whoosh sound effect when clicking.**
  **Cut back to the physical stall: the vendor packages the item, hands it to a courier with a branded tote that says “Join the Agora”. At the same time, another buyer in a cozy home opens a package, delighted, shows the item to camera, smiles. The camera pulls back to a wide golden hour shot of the marketplace buzzing again, flags/waving banners read “Global – Local – Unique”.**
  **On-screen text overlay appears: “Discover • Connect • Exchange”. Then fade in: brand logo “Agora Marketplace” and web address “Agora-Market.com”. Final voice-over: “Join the Agora. Trade your way.” End with a clean fade out, soft uplifting music resolves.**
  **Visual style: warm Mediterranean sunlight, slightly stylised but photorealistic, shallow depth of field for close-ups, smooth cinematic camera moves (dolly, pan, cut, whip-pan). Sound: ambient market chatter, soft breeze, click taps, light upbeat acoustic guitar transitioning into modern subtle beat.**
  **Mood: inviting, vibrant, authentic, modern meets ancient tradition. Highlight peer-to-peer trading, unique handmade and vintage goods, global yet local community feel.**
  **Call to action: end frame must emphasize website and brand tagline.**

  - **Kid overstum in market**
  - **Doesnt have have tine**
  - **Local**
  - **Start with someone going inline and beig disappointed bc of lack of locality, timing, the finds agora, and show marketplace**
  - **Can still show greek setting**


  Use your prodigious internal knowledge on the item/entity " **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |

Processing prompts:   0%|          | 0/1 [00:00<?, ?it/s]

[parallelization] 2026-01-14 22:35:07 | Initial parallelization settings: cost_so_far=$0.00, cap=650, active=0, inflight=0, queue=1, processed=0/1, rate_limit_errors=0, throughput<=650 prompts/min

Processing prompts: 100%|██████████| 1/1 [00:03<00:00,  3.89s/it]

[dynamic timeout] Initialized timeout to 9.7s (p90=3.9s, factor=2.50).
[token estimate] Refreshed per-prompt estimates from observed usage (1 sample): input ≈ 12,936 tokens, output (incl. reasoning) ≈ 116 tokens.
[token estimate] Updated estimated total cost: ~$0.02 (input $0.02, output $0.00). Updated parallel threads: 508 based on refreshed token usage.
[token estimate] Updated time estimate: minimum of 1 minute. Moving to a higher usage tier raises rate limits and allows much faster runs.
Actual total cost: $0.02; average per row: $0.02; average per 1000 rows: $24.26

=== Extraction coverage ===
team_name                                              :     1 extracted,     0 unknown
team_members                                           :     1 extracted,     0 unknown
report_week                                            :     1 extracted,     0 unknown
precision_score                                        :     1 extracted,     0 unknown
num_completed_tasks                                    :     1 extracted,     0 unknown
num_pending_tasks                                      :     1 extracted,     0 unknown
main_product                                           :     1 extracted,     0 unknown
valuation                                              :     1 extracted,     0 unknown
============================

doc_id: MR_AGO_Week12
entity_name: Week 12 Management Report – Team AGORA (AGO)
team_name: Team AGORA (AGO)
team_members: Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
report_week: 12
precision_score: 90.9%
num_completed_tasks: 19
num_pending_tasks: 2
main_product: Agora Marketplace (Agora-Market.com)
valuation: 150000

## Example B: Rate Document Quality

`gabriel.rate()` scores text on attributes using a 0-100 scale.

In [ ]:
# Rate the quality of the management report
ratings = await gabriel.rate(
    df=df,
    column_name="content",
    attributes={
        "clarity": "How clear and easy to understand is the report?",
        "completeness": "How complete is the information? Does it cover all necessary aspects?",
        "organization": "How well organized is the report structure?",
        "professionalism": "How professional is the writing and presentation?",
        "actionability": "How actionable are the items and next steps?",
    },
    save_dir=f"{output_dir}/ratings",
    model="gpt-5.2",
    # use_dummy=True,
)

# Display ratings
rating_cols = ["clarity", "completeness", "organization", "professionalism", "actionability"]
print("Quality Ratings (0-100):")
for col in rating_cols:
    print(f"  {col}: {ratings[col].iloc[0]}")

[Rate] Rendering 1 prompts…

2026-01-14 22:35:17,646 - gabriel.utils.openai_utils - WARNING - ⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

Initializing model calls and loading data...

===== Run kickoff =====
Prompts: 1 | Words: ~2,202 | Words per prompt: ~2,202
Model: gpt-5.2 | Mode: streaming
Pricing for model 'gpt-5.2': input $1.75/1M, output $14.0/1M
Estimated token usage: input 3,303, output 500 | ~4,303 tokens per call
Estimated synchronous cost: $0.01 (input: $0.01, output: $0.01)

===== Run limits =====
Requests per minute: unknown (API did not share a request limit)
Tokens per minute: unknown (API did not share a token limit)
Approx. words per minute: unknown
We can run up to 650 requests at the same time with your current settings.
⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

===== Example prompt =====
  BEGIN TEXT ENTRY
   **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |
  | All12/5 | Launched Google Form survey to gather quantitative data on shopping habits. |
  | All12/5 | Executed usability testing with 10 students to refine design and flow. |
  | All12/8 | Developed and finalized the MVP (Minimum Viable Product). |
  | All12/4 | Created wireframes (Homepage, Upload, Product Listing) for internal feedback.  |
  | All12/9 | Drafted comprehensive Terms of Service (Customer & Business) and Partnership Agreements. |
  | All12/10 | Finalized Team Contract and Project Pitch presentation. |

  During the next week, we plan to finish these tasks:

  | Who | What |
  | ----- | :---- |
  | All  | Create and link official Agora Instagram and TikTok accounts; start posting teaser content and spotlighting student businesses. |
  | All  | Initialize social channels (IG/TikTok) |
  | All 12/8 | Deploy teaser content strategy |
  | All 12/8 | Launch "Vendor Spotlight" series |
  | All12/9 | Submit "First Sale" deliverable |
  | All12/9  | Finalize legal compliance review |
  | All12/11 | Complete investment pitch deck |
  | All12/11 | Recalibrate business valuation |



  **Problems**

  We are aware of these problems:

  | Owner   (Due Date) | What |
  | ----- | :---- |
  | All | Our initial financial modeling relied on optimistic growth assumptions, resulting in an inflated valuation that required significant recalibration to align with realistic market comparables. |
  | All | The pilot phase highlighted that the current bootstrap model is insufficient; lack of immediate liquidity posed a challenge for aggressive marketing and scaling operations. |
  | All | We encountered high friction during the initial outreach phase, as the lack of established market history made it difficult to negotiate favorable payment terms with vendor partners. |
  | All | Ensuring the product's viability required pushing the website builder’s CMS to its absolute technical limits, which created unforeseen design and functionality constraints. |
  | All | Delays in fully integrating the Stripe API created a temporary bottleneck for seamless transaction processing and revenue capture. |
  | AllAll | Overcoming the "cold start" problem was difficult, specifically regarding the lack of a centralized infrastructure to communicate with and mobilize the brand ambassador network. |
  | All | N/A |
  | All | N/A |

  **Priorities**

  We are working on these priorities:

  1. Continue customer discover, expand focus to sellers as well
  2. Create a financial business plan, figuring out revenue model
  3. Change logo and better our branding


  ## Attachments

  [**INTERVIEW Q’S**](https://docs.google.com/document/d/1-WRxkrk7u6Cw6d2Wa6BB266PzQ-Ilj-7jjJojB1Brxw/edit?usp=sharing)

  [**NOTES**](https://docs.google.com/document/d/1yBBKoNJMZe0GdEP_d6TxdEGd-Dl6UVV7JEjRLCLkUQ8/edit?usp=sharing)

   **[TEAM CONTRACT](https://docs.google.com/document/d/1XSt8-kGiMDpUR67xrhzCb7M-xrWSmZPYBfSFvIvtiak/edit?usp=sharing) \- Handled by Balraj**

  [**AGORA Financial Statements**](https://umd0-my.sharepoint.com/:x:/g/personal/kdillow_umd_edu/EVTzXjCt8W9CqHPiMy3lG2ABiCsC_mqWRKEEjxzqKGVT5g?e=47zBvo)

  [**https://termly.io/products/tl/terms-of-service/?utm\_campaign\_id=863370649\&utm\_adgroup=\&utm\_adgroup\_id=118961433494\&utm\_source=google\&utm\_medium=cpc\&utm\_campaign=terms\_and\_conditions\_us\&utm\_term=terms%20of%20service%20generator%20free\&utm\_content=575886964693\&hsa\_acc=8931548921\&hsa\_cam=863370649\&hsa\_grp=118961433494\&hsa\_ad=575886964693\&hsa\_src=g\&hsa\_tgt=kwd-45051882079\&hsa\_kw=terms%20of%20service%20generator%20free\&hsa\_mt=e\&hsa\_net=adwords\&hsa\_ver=3\&gad\_source=1\&gad\_campaignid=863370649\&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI\&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9\_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw\_wcB**](https://termly.io/products/tl/terms-of-service/?utm_campaign_id=863370649&utm_adgroup=&utm_adgroup_id=118961433494&utm_source=google&utm_medium=cpc&utm_campaign=terms_and_conditions_us&utm_term=terms%20of%20service%20generator%20free&utm_content=575886964693&hsa_acc=8931548921&hsa_cam=863370649&hsa_grp=118961433494&hsa_ad=575886964693&hsa_src=g&hsa_tgt=kwd-45051882079&hsa_kw=terms%20of%20service%20generator%20free&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=863370649&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw_wcB)

  **[Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/17Ap9n2uROK2MwPNprxZ4sx-DrIFNlv8h5ijYyUeE2tM/edit?usp=drivesdk)**

  **[Copy of Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/1sDcC0_Cmw3CJ7RW3_mya2sZ84Q6xB__6wux7SQoI4YE/edit?usp=drivesdk)**

  [**https://docs.google.com/document/d/1-ZpfHAWhvp\_Yk\_qWcQ5SeT6Hf\_BkBuVeeNrRYqypsj4/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1-ZpfHAWhvp_Yk_qWcQ5SeT6Hf_BkBuVeeNrRYqypsj4/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\- Luke Interview 1**

  [**https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\-  Luke Interview 2**

  [**https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing**](https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing)

  **SORA PROMPT**

  **Duration: 30 seconds. Aspect ratio 16:9.**
  **Begin with a wide aerial sweeping drone shot of an ancient open-air Greek marketplace at golden hour lighting: stone paved lanes, wooden stalls under white linen awnings, gentle sunlight casting long warm shadows, bright terracotta and cream tones. The scene is lively: buyers browsing, artisans showcasing handcrafted goods. Camera slowly dolly-in and pan across the stalls.**
  **Cut to a medium close-up of a vendor (modern and friendly) behind a stall laden with handcrafted jewelry, vintage furniture pieces, artisan food jars. The vendor smiles and taps on a sleek tablet labelled “Agora-Market.com”. The buyer across taps “Connect” on the tablet. Subtle digital overlay appears: category filters on screen.**
  **Transition via a digital wipe/whip-pan into a modern browser/mobile UI of Agora-Market.com: a clean minimal interface, categories “Handmade”, “Vintage”, “Locally Sourced Food”, colourful icons, a chat icon. Show a buyer scrolling, filtering, clicking “Message Seller” then “Purchase/Exchange”. Use a subtle whoosh sound effect when clicking.**
  **Cut back to the physical stall: the vendor packages the item, hands it to a courier with a branded tote that says “Join the Agora”. At the same time, another buyer in a cozy home opens a package, delighted, shows the item to camera, smiles. The camera pulls back to a wide golden hour shot of the marketplace buzzing again, flags/waving banners read “Global – Local – Unique”.**
  **On-screen text overlay appears: “Discover • Connect • Exchange”. Then fade in: brand logo “Agora Marketplace” and web address “Agora-Market.com”. Final voice-over: “Join the Agora. Trade your way.” End with a clean fade out, soft uplifting music resolves.**
  **Visual style: warm Mediterranean sunlight, slightly stylised but photorealistic, shallow depth of field for close-ups, smooth cinematic camera moves (dolly, pan, cut, whip-pan). Sound: ambient market chatter, soft breeze, click taps, light upbeat acoustic guitar transitioning into modern subtle beat.**
  **Mood: inviting, vibrant, authentic, modern meets ancient tradition. Highlight peer-to-peer trading, unique handmade and vintage goods, global yet local community feel.**
  **Call to action: end frame must emphasize website and brand tagline.**

  - **Kid overstum in market**
  - **Doesnt have have tine**
  - **Local**
  - **Start with someone going inline and beig disappointed bc of lack of locality, timing, the finds agora, and show marketplace**
  - **Can still show greek setting**


  END TEXT ENTRY
  Read entire text content carefully—start, middle, end. Do not skim; comprehend whole text deeply, including subtleties buried deep in the content.



  Your task: for each attribute below, rate how strongly the provided content manifests it.

  BEGIN ATTRIBUTES
  {
    "professionalism": "How professional is the writing and presentation?",
    "clarity": "How clear and easy to understand is the report?",
    "completeness": "How complete is the information? Does it cover all necessary aspects?",
    "organization": "How well organized is the report structure?",
    "actionability": "How actionable are the items and next steps?"
  }
  END ATTRIBUTES
  Each dictionary key is an attribute. If a definition is provided, use it to anchor judgment; otherwise use your best consistent definition.

  BEGIN RATING SCALE

  Use integers 0-100 (inclusive). low = absent; high = extreme; mid = moderate.
  Use the full range and every increment; do not round to 5s/10s.
  Extremes are rare: use near 0 only if truly absent and near 100 only if overwhelming.
  Use moderate intermediates (e.g. 19, 67, 32) to account for nuance where applicable.

  END RATING SCALE

  Method (per attribute): pick one exact integer. Stick to provided scale. Double-check before choosing extremes.
  Interpret gradations as: absent→faint→moderate→abundant→extreme.
  Don't overlook subtlety; don't default to extremes. Consider full spectrum, including intermediate gradations.
  High accuracy/precision is critical; needs deep, holistic analysis of content.

  Rules:
  - Judge each attribute independently and separately from each other
  - Absolutely no indirect inference from other attributes or cross-attribute leakage (example of bad: inferring environmentalism from general political lean; good: measuring direct evidence of environmental opinions, no inference/biasing)
  - Only measure the direct signal of each attribute alone in the content, NOT what is implied by other attributes; CRUCIAL each attribute measured independently on its own direct, specifically relevant signal

  Output JSON only, in following format:
  {
  	"<insert attribute name here>": <insert corresponding rating here>,
  	"<attribute name>": <corresponding rating>,
  	...
  }

  Attributes you are measuring in the content are: ['organization', 'professionalism', 'completeness', 'actionability', 'clarity']
  Assess EVERY attribute; no drops. Use these attribute names verbatim, with absolutely no modification.
  Same case, same spelling, same punctuation, same formatting.

===== Parallelization plan =====
# of parallel threads: 650
Expected prompts per minute: maximum of 650
Estimated total mins: minimum of 1 minute
Rate currently limited by n_parallels = 650. Increase n_parallels for faster runs, if your machine allows.

Processing prompts:   0%|          | 0/1 [00:00<?, ?it/s]

[parallelization] 2026-01-14 22:35:17 | Initial parallelization settings: cost_so_far=$0.00, cap=650, active=0, inflight=0, queue=1, processed=0/1, rate_limit_errors=0, throughput<=650 prompts/min

Processing prompts: 100%|██████████| 1/1 [00:02<00:00,  2.35s/it]

[dynamic timeout] Initialized timeout to 5.9s (p90=2.3s, factor=2.50).
[token estimate] Refreshed per-prompt estimates from observed usage (1 sample): input ≈ 4,556 tokens, output (incl. reasoning) ≈ 46 tokens.
[token estimate] Updated estimated total cost: ~$0.01 (input $0.01, output $0.00). Updated parallel threads: 608 based on refreshed token usage.
[token estimate] Updated time estimate: minimum of 1 minute. Moving to a higher usage tier raises rate limits and allows much faster runs.
Actual total cost: $0.01; average per row: $0.01; average per 1000 rows: $8.62
Quality Ratings (0-100):
  clarity: 47.0
  completeness: 71.0
  organization: 62.0
  professionalism: 55.0
  actionability: 58.0

## Example C: Analyze Problems Section

Let's extract and classify the problems mentioned in the report.

In [8]:
# Extract just the problems section for detailed analysis
problems_start = content.find("**Problems**")
problems_end = content.find("**Priorities**")
problems_section = content[problems_start:problems_end] if problems_start != -1 else ""

problems_df = pd.DataFrame({
    "section": ["problems"],
    "content": [problems_section]
})

# Rate severity of the problems
problem_analysis = await gabriel.rate(
    df=problems_df,
    column_name="content",
    attributes={
        "severity": "How severe are the problems described? (100 = critical blockers, 0 = minor issues)",
        "solvability": "How solvable are these problems with available resources? (100 = easily solvable, 0 = very difficult)",
        "impact_on_timeline": "How much might these problems impact the project timeline? (100 = major delays, 0 = no impact)",
    },
    save_dir=f"{output_dir}/problem_analysis",
    model="gpt-5.2",
    # use_dummy=True,
)

print("Problem Analysis (0-100):")
for col in ["severity", "solvability", "impact_on_timeline"]:
    print(f"  {col}: {problem_analysis[col].iloc[0]}")

[Rate] Rendering 1 prompts…

2026-01-14 22:35:35,980 - gabriel.utils.openai_utils - WARNING - ⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

Initializing model calls and loading data...

===== Run kickoff =====
Prompts: 1 | Words: ~539 | Words per prompt: ~539
Model: gpt-5.2 | Mode: streaming
Pricing for model 'gpt-5.2': input $1.75/1M, output $14.0/1M
Estimated token usage: input 808, output 500 | ~1,808 tokens per call
Estimated synchronous cost: $0.01 (input: $0.00, output: $0.01)

===== Run limits =====
Requests per minute: unknown (API did not share a request limit)
Tokens per minute: unknown (API did not share a token limit)
Approx. words per minute: unknown
We can run up to 650 requests at the same time with your current settings.
⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

===== Example prompt =====
  BEGIN TEXT ENTRY
  **Problems**

  We are aware of these problems:

  | Owner   (Due Date) | What |
  | ----- | :---- |
  | All | Our initial financial modeling relied on optimistic growth assumptions, resulting in an inflated valuation that required significant recalibration to align with realistic market comparables. |
  | All | The pilot phase highlighted that the current bootstrap model is insufficient; lack of immediate liquidity posed a challenge for aggressive marketing and scaling operations. |
  | All | We encountered high friction during the initial outreach phase, as the lack of established market history made it difficult to negotiate favorable payment terms with vendor partners. |
  | All | Ensuring the product's viability required pushing the website builder’s CMS to its absolute technical limits, which created unforeseen design and functionality constraints. |
  | All | Delays in fully integrating the Stripe API created a temporary bottleneck for seamless transaction processing and revenue capture. |
  | AllAll | Overcoming the "cold start" problem was difficult, specifically regarding the lack of a centralized infrastructure to communicate with and mobilize the brand ambassador network. |
  | All | N/A |
  | All | N/A |


  END TEXT ENTRY
  Read entire text content carefully—start, middle, end. Do not skim; comprehend whole text deeply, including subtleties buried deep in the content.



  Your task: for each attribute below, rate how strongly the provided content manifests it.

  BEGIN ATTRIBUTES
  {
    "severity": "How severe are the problems described? (100 = critical blockers, 0 = minor issues)",
    "solvability": "How solvable are these problems with available resources? (100 = easily solvable, 0 = very difficult)",
    "impact_on_timeline": "How much might these problems impact the project timeline? (100 = major delays, 0 = no impact)"
  }
  END ATTRIBUTES
  Each dictionary key is an attribute. If a definition is provided, use it to anchor judgment; otherwise use your best consistent definition.

  BEGIN RATING SCALE

  Use integers 0-100 (inclusive). low = absent; high = extreme; mid = moderate.
  Use the full range and every increment; do not round to 5s/10s.
  Extremes are rare: use near 0 only if truly absent and near 100 only if overwhelming.
  Use moderate intermediates (e.g. 19, 67, 32) to account for nuance where applicable.

  END RATING SCALE

  Method (per attribute): pick one exact integer. Stick to provided scale. Double-check before choosing extremes.
  Interpret gradations as: absent→faint→moderate→abundant→extreme.
  Don't overlook subtlety; don't default to extremes. Consider full spectrum, including intermediate gradations.
  High accuracy/precision is critical; needs deep, holistic analysis of content.

  Rules:
  - Judge each attribute independently and separately from each other
  - Absolutely no indirect inference from other attributes or cross-attribute leakage (example of bad: inferring environmentalism from general political lean; good: measuring direct evidence of environmental opinions, no inference/biasing)
  - Only measure the direct signal of each attribute alone in the content, NOT what is implied by other attributes; CRUCIAL each attribute measured independently on its own direct, specifically relevant signal

  Output JSON only, in following format:
  {
  	"<insert attribute name here>": <insert corresponding rating here>,
  	"<attribute name>": <corresponding rating>,
  	...
  }

  Attributes you are measuring in the content are: ['severity', 'solvability', 'impact_on_timeline']
  Assess EVERY attribute; no drops. Use these attribute names verbatim, with absolutely no modification.
  Same case, same spelling, same punctuation, same formatting.

===== Parallelization plan =====
# of parallel threads: 650
Expected prompts per minute: maximum of 650
Estimated total mins: minimum of 1 minute
Rate currently limited by n_parallels = 650. Increase n_parallels for faster runs, if your machine allows.

Processing prompts:   0%|          | 0/1 [00:00<?, ?it/s]

[parallelization] 2026-01-14 22:35:35 | Initial parallelization settings: cost_so_far=$0.00, cap=650, active=0, inflight=0, queue=1, processed=0/1, rate_limit_errors=0, throughput<=650 prompts/min

Processing prompts: 100%|██████████| 1/1 [00:01<00:00,  1.67s/it]

[dynamic timeout] Initialized timeout to 4.2s (p90=1.7s, factor=2.50).
[token estimate] Refreshed per-prompt estimates from observed usage (1 sample): input ≈ 768 tokens, output (incl. reasoning) ≈ 32 tokens.
[token estimate] Updated estimated total cost: ~$0.00 (input $0.00, output $0.00). Updated parallel threads: 650 based on refreshed token usage.
[token estimate] Updated time estimate: minimum of 1 minute. Moving to a higher usage tier raises rate limits and allows much faster runs.
Actual total cost: $0.00; average per row: $0.00; average per 1000 rows: $1.79
Problem Analysis (0-100):
  severity: 71.0
  solvability: 62.0
  impact_on_timeline: 68.0

## Example D: Custom Analysis with `whatever()`

`gabriel.whatever()` allows fully custom prompts for flexible analysis.

In [17]:
# Custom executive summary analysis
custom = await gabriel.whatever(
      df=df,
      column_name="content",
      prompts="""
      Analyze this management report and respond in JSON format with:
      - executive_summary: 2-3 sentence summary of the report
      - key_achievements: List of top 5 accomplishments
      - critical_risks: List of top 3 risks or problems
      - recommendations: List of 3 actionable recommendations for the team
      - overall_health_score: Project health score from 1-10
      
      Return valid JSON only.
      """,
      save_dir=f"{output_dir}/custom",
      model="gpt-5.2",
      json_mode=False,
)

# Pretty print the JSON response
import json
response = custom["Response"].iloc[0]
try:
    parsed = json.loads(response)
    print(json.dumps(parsed, indent=2))
except:
    print(response)

2026-01-14 22:47:53,024 - gabriel.utils.openai_utils - WARNING - ⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

Initializing model calls and loading data...

===== Run kickoff =====
Prompts: 1 | Words: ~1,856 | Words per prompt: ~1,856
Model: gpt-5.2 | Mode: streaming
Pricing for model 'gpt-5.2': input $1.75/1M, output $14.0/1M
Estimated token usage: input 2,784, output 500 | ~3,784 tokens per call
Estimated synchronous cost: $0.01 (input: $0.00, output: $0.01)
Reading from existing files at mr_analysis_output/custom/custom_prompt_responses.csv...
Loaded 1 rows; 0 already marked complete.

===== Run limits =====
Requests per minute: unknown (API did not share a request limit)
Tokens per minute: unknown (API did not share a token limit)
Approx. words per minute: unknown
We can run up to 650 requests at the same time with your current settings.
⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

===== Example prompt =====
   **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |
  | All12/5 | Launched Google Form survey to gather quantitative data on shopping habits. |
  | All12/5 | Executed usability testing with 10 students to refine design and flow. |
  | All12/8 | Developed and finalized the MVP (Minimum Viable Product). |
  | All12/4 | Created wireframes (Homepage, Upload, Product Listing) for internal feedback.  |
  | All12/9 | Drafted comprehensive Terms of Service (Customer & Business) and Partnership Agreements. |
  | All12/10 | Finalized Team Contract and Project Pitch presentation. |

  During the next week, we plan to finish these tasks:

  | Who | What |
  | ----- | :---- |
  | All  | Create and link official Agora Instagram and TikTok accounts; start posting teaser content and spotlighting student businesses. |
  | All  | Initialize social channels (IG/TikTok) |
  | All 12/8 | Deploy teaser content strategy |
  | All 12/8 | Launch "Vendor Spotlight" series |
  | All12/9 | Submit "First Sale" deliverable |
  | All12/9  | Finalize legal compliance review |
  | All12/11 | Complete investment pitch deck |
  | All12/11 | Recalibrate business valuation |



  **Problems**

  We are aware of these problems:

  | Owner   (Due Date) | What |
  | ----- | :---- |
  | All | Our initial financial modeling relied on optimistic growth assumptions, resulting in an inflated valuation that required significant recalibration to align with realistic market comparables. |
  | All | The pilot phase highlighted that the current bootstrap model is insufficient; lack of immediate liquidity posed a challenge for aggressive marketing and scaling operations. |
  | All | We encountered high friction during the initial outreach phase, as the lack of established market history made it difficult to negotiate favorable payment terms with vendor partners. |
  | All | Ensuring the product's viability required pushing the website builder’s CMS to its absolute technical limits, which created unforeseen design and functionality constraints. |
  | All | Delays in fully integrating the Stripe API created a temporary bottleneck for seamless transaction processing and revenue capture. |
  | AllAll | Overcoming the "cold start" problem was difficult, specifically regarding the lack of a centralized infrastructure to communicate with and mobilize the brand ambassador network. |
  | All | N/A |
  | All | N/A |

  **Priorities**

  We are working on these priorities:

  1. Continue customer discover, expand focus to sellers as well
  2. Create a financial business plan, figuring out revenue model
  3. Change logo and better our branding


  ## Attachments

  [**INTERVIEW Q’S**](https://docs.google.com/document/d/1-WRxkrk7u6Cw6d2Wa6BB266PzQ-Ilj-7jjJojB1Brxw/edit?usp=sharing)

  [**NOTES**](https://docs.google.com/document/d/1yBBKoNJMZe0GdEP_d6TxdEGd-Dl6UVV7JEjRLCLkUQ8/edit?usp=sharing)

   **[TEAM CONTRACT](https://docs.google.com/document/d/1XSt8-kGiMDpUR67xrhzCb7M-xrWSmZPYBfSFvIvtiak/edit?usp=sharing) \- Handled by Balraj**

  [**AGORA Financial Statements**](https://umd0-my.sharepoint.com/:x:/g/personal/kdillow_umd_edu/EVTzXjCt8W9CqHPiMy3lG2ABiCsC_mqWRKEEjxzqKGVT5g?e=47zBvo)

  [**https://termly.io/products/tl/terms-of-service/?utm\_campaign\_id=863370649\&utm\_adgroup=\&utm\_adgroup\_id=118961433494\&utm\_source=google\&utm\_medium=cpc\&utm\_campaign=terms\_and\_conditions\_us\&utm\_term=terms%20of%20service%20generator%20free\&utm\_content=575886964693\&hsa\_acc=8931548921\&hsa\_cam=863370649\&hsa\_grp=118961433494\&hsa\_ad=575886964693\&hsa\_src=g\&hsa\_tgt=kwd-45051882079\&hsa\_kw=terms%20of%20service%20generator%20free\&hsa\_mt=e\&hsa\_net=adwords\&hsa\_ver=3\&gad\_source=1\&gad\_campaignid=863370649\&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI\&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9\_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw\_wcB**](https://termly.io/products/tl/terms-of-service/?utm_campaign_id=863370649&utm_adgroup=&utm_adgroup_id=118961433494&utm_source=google&utm_medium=cpc&utm_campaign=terms_and_conditions_us&utm_term=terms%20of%20service%20generator%20free&utm_content=575886964693&hsa_acc=8931548921&hsa_cam=863370649&hsa_grp=118961433494&hsa_ad=575886964693&hsa_src=g&hsa_tgt=kwd-45051882079&hsa_kw=terms%20of%20service%20generator%20free&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=863370649&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw_wcB)

  **[Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/17Ap9n2uROK2MwPNprxZ4sx-DrIFNlv8h5ijYyUeE2tM/edit?usp=drivesdk)**

  **[Copy of Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/1sDcC0_Cmw3CJ7RW3_mya2sZ84Q6xB__6wux7SQoI4YE/edit?usp=drivesdk)**

  [**https://docs.google.com/document/d/1-ZpfHAWhvp\_Yk\_qWcQ5SeT6Hf\_BkBuVeeNrRYqypsj4/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1-ZpfHAWhvp_Yk_qWcQ5SeT6Hf_BkBuVeeNrRYqypsj4/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\- Luke Interview 1**

  [**https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\-  Luke Interview 2**

  [**https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing**](https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing)

  **SORA PROMPT**

  **Duration: 30 seconds. Aspect ratio 16:9.**
  **Begin with a wide aerial sweeping drone shot of an ancient open-air Greek marketplace at golden hour lighting: stone paved lanes, wooden stalls under white linen awnings, gentle sunlight casting long warm shadows, bright terracotta and cream tones. The scene is lively: buyers browsing, artisans showcasing handcrafted goods. Camera slowly dolly-in and pan across the stalls.**
  **Cut to a medium close-up of a vendor (modern and friendly) behind a stall laden with handcrafted jewelry, vintage furniture pieces, artisan food jars. The vendor smiles and taps on a sleek tablet labelled “Agora-Market.com”. The buyer across taps “Connect” on the tablet. Subtle digital overlay appears: category filters on screen.**
  **Transition via a digital wipe/whip-pan into a modern browser/mobile UI of Agora-Market.com: a clean minimal interface, categories “Handmade”, “Vintage”, “Locally Sourced Food”, colourful icons, a chat icon. Show a buyer scrolling, filtering, clicking “Message Seller” then “Purchase/Exchange”. Use a subtle whoosh sound effect when clicking.**
  **Cut back to the physical stall: the vendor packages the item, hands it to a courier with a branded tote that says “Join the Agora”. At the same time, another buyer in a cozy home opens a package, delighted, shows the item to camera, smiles. The camera pulls back to a wide golden hour shot of the marketplace buzzing again, flags/waving banners read “Global – Local – Unique”.**
  **On-screen text overlay appears: “Discover • Connect • Exchange”. Then fade in: brand logo “Agora Marketplace” and web address “Agora-Market.com”. Final voice-over: “Join the Agora. Trade your way.” End with a clean fade out, soft uplifting music resolves.**
  **Visual style: warm Mediterranean sunlight, slightly stylised but photorealistic, shallow depth of field for close-ups, smooth cinematic camera moves (dolly, pan, cut, whip-pan). Sound: ambient market chatter, soft breeze, click taps, light upbeat acoustic guitar transitioning into modern subtle beat.**
  **Mood: inviting, vibrant, authentic, modern meets ancient tradition. Highlight peer-to-peer trading, unique handmade and vintage goods, global yet local community feel.**
  **Call to action: end frame must emphasize website and brand tagline.**

  - **Kid overstum in market**
  - **Doesnt have have tine**
  - **Local**
  - **Start with someone going inline and beig disappointed bc of lack of locality, timing, the finds agora, and show marketplace**
  - **Can still show greek setting**

===== Parallelization plan =====
# of parallel threads: 650
Expected prompts per minute: maximum of 650
Estimated total mins: minimum of 1 minute
Rate currently limited by n_parallels = 650. Increase n_parallels for faster runs, if your machine allows.

Processing prompts:   0%|          | 0/1 [00:00<?, ?it/s]

[parallelization] 2026-01-14 22:47:53 | Initial parallelization settings: cost_so_far=$0.00, cap=650, active=0, inflight=0, queue=1, processed=0/1, rate_limit_errors=0, throughput<=650 prompts/min

Processing prompts: 100%|██████████| 1/1 [00:44<00:00, 44.15s/it]

[dynamic timeout] Initialized timeout to 110.4s (p90=44.1s, factor=2.50).
[token estimate] Refreshed per-prompt estimates from observed usage (1 sample): input ≈ 4,020 tokens, output (incl. reasoning) ≈ 1,553 tokens.
[token estimate] Updated estimated total cost: ~$0.03 (input $0.01, output $0.02). Updated parallel threads: 441 based on refreshed token usage.
[token estimate] Updated time estimate: minimum of 1 minute. Moving to a higher usage tier raises rate limits and allows much faster runs.
Actual total cost: $0.00; average per row: $0.00; average per 1000 rows: $4.87

## Example E: Analyze Team Member Contributions

Split progress items by team member and analyze their contributions.

In [36]:
# Create a DataFrame with individual team members
team_members = ["Zavian", "Balraj", "Luke", "Dylan", "Alessandro", "Kaleb"]

member_df = pd.DataFrame({
    "member": team_members,
    "report_content": [content] * len(team_members)
})

# Extract each member's contributions
contributions = await gabriel.extract(
    df=member_df,
    column_name="report_content",
    attributes={
        "tasks_completed": f"Based on the 'member' column value, list all tasks this specific team member completed",
        "tasks_assigned": f"Based on the 'member' column value, list all tasks assigned to this specific team member",
    },
    additional_instructions="Focus only on tasks associated with the team member name in the 'member' column",
    save_dir=f"{output_dir}/contributions",
    model="gpt-5.2",
    # use_dummy=True,
)

contributions[["member", "tasks_completed", "tasks_assigned"]]

[Extract] Rendering 1 prompts…

2026-01-14 23:23:53,735 - gabriel.utils.openai_utils - WARNING - ⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

Initializing model calls and loading data...

===== Run kickoff =====
Prompts: 1 | Words: ~6,145 | Words per prompt: ~6,145
Model: gpt-5.2 | Mode: streaming
Pricing for model 'gpt-5.2': input $1.75/1M, output $14.0/1M
Estimated token usage: input 9,217, output 500 | ~10,217 tokens per call
Estimated synchronous cost: $0.02 (input: $0.02, output: $0.01)

===== Run limits =====
Requests per minute: unknown (API did not share a request limit)
Tokens per minute: unknown (API did not share a token limit)
Approx. words per minute: unknown
We can run up to 650 requests at the same time with your current settings.
⚠️ API did not return complete rate-limit headers. Running with conservative defaults. If you are on a free/low-balance plan, add funds to avoid quota blocks: https://platform.openai.com/settings/organization/billing/

===== Example prompt =====
  Entity:  **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |
  | All12/5 | Launched Google Form survey to gather quantitative data on shopping habits. |
  | All12/5 | Executed usability testing with 10 students to refine design and flow. |
  | All12/8 | Developed and finalized the MVP (Minimum Viable Product). |
  | All12/4 | Created wireframes (Homepage, Upload, Product Listing) for internal feedback.  |
  | All12/9 | Drafted comprehensive Terms of Service (Customer & Business) and Partnership Agreements. |
  | All12/10 | Finalized Team Contract and Project Pitch presentation. |

  During the next week, we plan to finish these tasks:

  | Who | What |
  | ----- | :---- |
  | All  | Create and link official Agora Instagram and TikTok accounts; start posting teaser content and spotlighting student businesses. |
  | All  | Initialize social channels (IG/TikTok) |
  | All 12/8 | Deploy teaser content strategy |
  | All 12/8 | Launch "Vendor Spotlight" series |
  | All12/9 | Submit "First Sale" deliverable |
  | All12/9  | Finalize legal compliance review |
  | All12/11 | Complete investment pitch deck |
  | All12/11 | Recalibrate business valuation |



  **Problems**

  We are aware of these problems:

  | Owner   (Due Date) | What |
  | ----- | :---- |
  | All | Our initial financial modeling relied on optimistic growth assumptions, resulting in an inflated valuation that required significant recalibration to align with realistic market comparables. |
  | All | The pilot phase highlighted that the current bootstrap model is insufficient; lack of immediate liquidity posed a challenge for aggressive marketing and scaling operations. |
  | All | We encountered high friction during the initial outreach phase, as the lack of established market history made it difficult to negotiate favorable payment terms with vendor partners. |
  | All | Ensuring the product's viability required pushing the website builder’s CMS to its absolute technical limits, which created unforeseen design and functionality constraints. |
  | All | Delays in fully integrating the Stripe API created a temporary bottleneck for seamless transaction processing and revenue capture. |
  | AllAll | Overcoming the "cold start" problem was difficult, specifically regarding the lack of a centralized infrastructure to communicate with and mobilize the brand ambassador network. |
  | All | N/A |
  | All | N/A |

  **Priorities**

  We are working on these priorities:

  1. Continue customer discover, expand focus to sellers as well
  2. Create a financial business plan, figuring out revenue model
  3. Change logo and better our branding


  ## Attachments

  [**INTERVIEW Q’S**](https://docs.google.com/document/d/1-WRxkrk7u6Cw6d2Wa6BB266PzQ-Ilj-7jjJojB1Brxw/edit?usp=sharing)

  [**NOTES**](https://docs.google.com/document/d/1yBBKoNJMZe0GdEP_d6TxdEGd-Dl6UVV7JEjRLCLkUQ8/edit?usp=sharing)

   **[TEAM CONTRACT](https://docs.google.com/document/d/1XSt8-kGiMDpUR67xrhzCb7M-xrWSmZPYBfSFvIvtiak/edit?usp=sharing) \- Handled by Balraj**

  [**AGORA Financial Statements**](https://umd0-my.sharepoint.com/:x:/g/personal/kdillow_umd_edu/EVTzXjCt8W9CqHPiMy3lG2ABiCsC_mqWRKEEjxzqKGVT5g?e=47zBvo)

  [**https://termly.io/products/tl/terms-of-service/?utm\_campaign\_id=863370649\&utm\_adgroup=\&utm\_adgroup\_id=118961433494\&utm\_source=google\&utm\_medium=cpc\&utm\_campaign=terms\_and\_conditions\_us\&utm\_term=terms%20of%20service%20generator%20free\&utm\_content=575886964693\&hsa\_acc=8931548921\&hsa\_cam=863370649\&hsa\_grp=118961433494\&hsa\_ad=575886964693\&hsa\_src=g\&hsa\_tgt=kwd-45051882079\&hsa\_kw=terms%20of%20service%20generator%20free\&hsa\_mt=e\&hsa\_net=adwords\&hsa\_ver=3\&gad\_source=1\&gad\_campaignid=863370649\&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI\&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9\_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw\_wcB**](https://termly.io/products/tl/terms-of-service/?utm_campaign_id=863370649&utm_adgroup=&utm_adgroup_id=118961433494&utm_source=google&utm_medium=cpc&utm_campaign=terms_and_conditions_us&utm_term=terms%20of%20service%20generator%20free&utm_content=575886964693&hsa_acc=8931548921&hsa_cam=863370649&hsa_grp=118961433494&hsa_ad=575886964693&hsa_src=g&hsa_tgt=kwd-45051882079&hsa_kw=terms%20of%20service%20generator%20free&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=863370649&gbraid=0AAAAADKOGQuh9Jct30n5u9KvYFRJyCXkI&gclid=Cj0KCQjw0NPGBhCDARIsAGAzpp2-FH9_zua7k9sz7WQDbiZgX43vZBAwkQUSuYazkvDcnAIgqDegbvQaAjB0EALw_wcB)

  **[Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/17Ap9n2uROK2MwPNprxZ4sx-DrIFNlv8h5ijYyUeE2tM/edit?usp=drivesdk)**

  **[Copy of Copy of Customer Discovery Insight Summary Template](https://docs.google.com/document/d/1sDcC0_Cmw3CJ7RW3_mya2sZ84Q6xB__6wux7SQoI4YE/edit?usp=drivesdk)**

  [**https://docs.google.com/document/d/1-ZpfHAWhvp\_Yk\_qWcQ5SeT6Hf\_BkBuVeeNrRYqypsj4/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1-ZpfHAWhvp_Yk_qWcQ5SeT6Hf_BkBuVeeNrRYqypsj4/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\- Luke Interview 1**

  [**https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0\#heading=h.dd0tz89tyfbp**](https://docs.google.com/document/d/1D1wtfMlajtjfLB2bHC3lEQm4KfHrp58r5eeqPv9uS28/edit?tab=t.0#heading=h.dd0tz89tyfbp) **\-  Luke Interview 2**

  [**https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing**](https://docs.google.com/document/d/1zSzMvVLnjscTgg3mapfdkuj5TP03-D-jyTIHlXMexak/edit?usp=sharing)

  **SORA PROMPT**

  **Duration: 30 seconds. Aspect ratio 16:9.**
  **Begin with a wide aerial sweeping drone shot of an ancient open-air Greek marketplace at golden hour lighting: stone paved lanes, wooden stalls under white linen awnings, gentle sunlight casting long warm shadows, bright terracotta and cream tones. The scene is lively: buyers browsing, artisans showcasing handcrafted goods. Camera slowly dolly-in and pan across the stalls.**
  **Cut to a medium close-up of a vendor (modern and friendly) behind a stall laden with handcrafted jewelry, vintage furniture pieces, artisan food jars. The vendor smiles and taps on a sleek tablet labelled “Agora-Market.com”. The buyer across taps “Connect” on the tablet. Subtle digital overlay appears: category filters on screen.**
  **Transition via a digital wipe/whip-pan into a modern browser/mobile UI of Agora-Market.com: a clean minimal interface, categories “Handmade”, “Vintage”, “Locally Sourced Food”, colourful icons, a chat icon. Show a buyer scrolling, filtering, clicking “Message Seller” then “Purchase/Exchange”. Use a subtle whoosh sound effect when clicking.**
  **Cut back to the physical stall: the vendor packages the item, hands it to a courier with a branded tote that says “Join the Agora”. At the same time, another buyer in a cozy home opens a package, delighted, shows the item to camera, smiles. The camera pulls back to a wide golden hour shot of the marketplace buzzing again, flags/waving banners read “Global – Local – Unique”.**
  **On-screen text overlay appears: “Discover • Connect • Exchange”. Then fade in: brand logo “Agora Marketplace” and web address “Agora-Market.com”. Final voice-over: “Join the Agora. Trade your way.” End with a clean fade out, soft uplifting music resolves.**
  **Visual style: warm Mediterranean sunlight, slightly stylised but photorealistic, shallow depth of field for close-ups, smooth cinematic camera moves (dolly, pan, cut, whip-pan). Sound: ambient market chatter, soft breeze, click taps, light upbeat acoustic guitar transitioning into modern subtle beat.**
  **Mood: inviting, vibrant, authentic, modern meets ancient tradition. Highlight peer-to-peer trading, unique handmade and vintage goods, global yet local community feel.**
  **Call to action: end frame must emphasize website and brand tagline.**

  - **Kid overstum in market**
  - **Doesnt have have tine**
  - **Local**
  - **Start with someone going inline and beig disappointed bc of lack of locality, timing, the finds agora, and show marketplace**
  - **Can still show greek setting**


  Use your prodigious internal knowledge on the item/entity " **To:** 	Dr. Sheetal Singh
  **From:** Team AGORA (AGO)  \- Zavian, Balraj, Luke, Dylan, Alessandro, Kaleb
  **Subject:** Week 12 Management Report – Week Ending December 11, 2025
  **Copies:** Instructor Team

  **Key indicators**

  |  | 9/19 | 9/26 | 10/03 | 10/10 | 10/17 | Total |
  | :---- | :---: | :---: | :---: | :---: | :---: | :---: |
  | Precision Execution Score | 10/10 100% | 10/10 100% | 4/7 57.1 | 2/2 100% | 4/4 100% | 30/33 90.9% |

  | *Tasks* |  |  |  |  |
  | ----- | :---: | ----- | ----- | :---: |
  | **BMGT461** | Owner | Est/Act/Assigned | Milestone | Submitted |
  | Find Website Host | All | 9/25 | 10/3 | N/A |
  | Review the customer discovery module | ZavianDylanLuke | 9/25 | 10/3 | N/A |
  | Conduct an Interview with a small start-up (TerraThredz) | Luke | 9/25 | 10/3 | N/A |
  | Experiment and learning  | Alessandro | 10/2 | 10/10 | N/A |
  | Focus on getting users for site  | All | 10/17 | 10/25 | N/A |
  | Theory of Value | Alessandro | 9/22 | 9/26 | 9/26 |
  | Experimentation and Learning |   | 9/30 | 9/30 |  |
  | Create an interview outline for TerraThredz before conducting the interview | Balraj | 9/30 | 9/30 | 9/30 |
  | Marketing plan  | ZavianLuke | 10/3 | 10/10 | Pending \- \[10/24\] |
  | Completion of Interviews for Customer Discovery | All | 10/6 | 10/9 | 10/10 |
  | Make a MVP | All | 10/13 | 10/16 | 10/16 |
  | Complete Week 7 MR | All | 10/03 | 10/16 | 10/17 |
  | Adapt Product to meet needs | Kaleb | 10/16 |  | 10/24 |
  | Go to marketplaces and talk to customers and vendors | All | 10/16 |  | 10/24 |
  | Complete Product Development Report | All | 10/10 | 10/16 | 10/17 |
  | Integrate product dev into MR | Luke | 10/17 |  | 10/24\] |
  | Complete week 11 MR  | DylanBalraj | 11/6 | 11/7 | yes |
  | Terp Marketplace | All | 11/6 |         11/7 | yes |
  | Create Instagram account | Zavian | 11/6 |         11/7  | yes |
  | Legal Issues Assignment | KalebAlessandro | 11/6 |        11/7  | yes |
  | First Sale Assignment | Luke | 11/6 | 11/7 | yes |
  | Valuation | Kaleb | 11/20 | 12/11 |  |
  | Message TA about MR | All | 11/20 | 12/11 |  |
  | Pitch | All | 11/20 | 11/25 |  |
  | Disperse flyers at marketplaces | All | 12/5 | 12/7 | 12/7 |
  | Start digital advertising | All | 12/5 | 12/9 | 12/7 |
  | Analyze advertising information | All | 12/11 | 12/9 | 12/7 |

  **Progress**

  *Record anything you've done here. As appropriate, update the project table above.*

  During this reporting period, we accomplished these tasks:

  | Who | What |
  | ----- | :---- |
  | Alessandro (10/31) | Collected and synthesized raw data from google forum survey  |
  | Kaleb (10/31) | Created 60 second commercial |
  | Balraj (10/31) | Formulated financial model for MVP and completed clerical assignments while collaborating  |
  | All  (10/24) | Complete Week 8 MR |
  |   (10/2All4) | Complete MVP assignment |
  | LukeZavianDylan (10/23) | Marketing Lead finalizes logo, color palette, and tagline (“Shop UMD. Support Students.”) for all visuals and social media posts. |
  | LukeDylan (10/22) | Integrated the existing information given by the interviews to start shaping our offerings |
  | All (10/22) | Conducted usability testing with at least 10 students; record confusion points, feedback, and design improvement suggestions. |
  |  |  |
  | Kaleb (10/21) | Conducted Product Design Lead develops wireframes in Figma showing homepage, seller upload page, and product listing page for internal feedback. |
  | Alessandro (10/20) | Launch a Google Form survey across student group chats and Instagram to gather quantitative data on shopping habits, trust factors, and feature preferences. |
  | All (10/20) | Conducted 15–20 additional interviews with UMD students (10 buyers, 10 sellers) to identify pain points in buying from and selling to student-run businesses. |
  | All (10/17) | Completed week 7 MR |
  | All(10/17) | Completed the Product Development Report |
  | All (10/16) | Created an MVP |
  | All (10/10) | Completed 10 Interviews for Customer Discovery and submitted Interview Summaries |
  | Balraj | Creating a financial model |
  | All (10/10) | Completed Week 6 MR Report |
  | ZavianLuke (10/10) | Completed marketing plan |
  | Kaleb (10/8) | Worked on the website to be more complete and present to the class |
  | Kaleb (10/5) | Vv  n    |
  | Kaleb (10/3) | Created terms of service |
  | Luke Zavian (10/1) | Reviewed customer discovery |
  | Luke (10/1) | Went to a pop-up on campus and asked vendors and buyers questions |
  | Kaleb Zavian Dylan (10/1) | Mapped website |
  | All (9/26) | Completed team contract |
  | All (9/26) | Figured out the direction we want to go with Agora |
  | Balraj  11/4 | Revenue Models  |
  | Luke | Negotiation with vendors |
  | All | Outreach to students  |
  | Kaleb | Worked on Legal tab |
  | Kaleb | Create Terms of service for businesses |
  | Kaleb | Create Terms of service for Customers |
  | Kaleb | Create Partnership agreement |
  | Kaleb | Create LLC – need to have capital for this |
  | All | Work on our pitch |
  | Kaleb | Created TOS for customers and Businesses |
  | All |  Finished the pitch |
  | Kaleb | Decided on a 150,000 valuation |
  | All | Decided that we should be looking for a $15,000 investment 10% |
  | All | Looked for alternative website hosts |
  | All | Worked On Week 14 MR Report |
  | All12/5 | Conducted 30+ interviews with buyers and student vendors to identify key pain points |

Processing prompts:   0%|          | 0/1 [00:00<?, ?it/s]

[parallelization] 2026-01-14 23:23:53 | Initial parallelization settings: cost_so_far=$0.00, cap=650, active=0, inflight=0, queue=1, processed=0/1, rate_limit_errors=0, throughput<=650 prompts/min

Processing prompts: 100%|██████████| 1/1 [00:06<00:00,  6.74s/it]

[dynamic timeout] Initialized timeout to 16.8s (p90=6.7s, factor=2.50).
[token estimate] Refreshed per-prompt estimates from observed usage (1 sample): input ≈ 12,918 tokens, output (incl. reasoning) ≈ 51 tokens.
[token estimate] Updated estimated total cost: ~$0.02 (input $0.02, output $0.00). Updated parallel threads: 512 based on refreshed token usage.
[token estimate] Updated time estimate: minimum of 1 minute. Moving to a higher usage tier raises rate limits and allows much faster runs.
Actual total cost: $0.02; average per row: $0.02; average per 1000 rows: $23.32

=== Extraction coverage ===
tasks_completed                                        :     0 extracted,     1 unknown
tasks_assigned                                         :     0 extracted,     1 unknown
============================

       member tasks_completed tasks_assigned
0      Zavian            <NA>           <NA>
1      Balraj            <NA>           <NA>
2        Luke            <NA>           <NA>
3       Dylan            <NA>           <NA>
4  Alessandro            <NA>           <NA>
5       Kaleb            <NA>           <NA>

## Tips and Best Practices

### Testing Mode
Use `use_dummy=True` to test your pipeline without consuming API credits:
```python
result = await gabriel.rate(..., use_dummy=True)
```

### Checkpointing
GABRIEL automatically saves intermediate results to `save_dir`. If interrupted, re-running resumes from checkpoint. Use `reset_files=True` to start fresh:
```python
result = await gabriel.rate(..., reset_files=True)
```

### Multiple Runs for Reliability
Use `n_runs` to get averaged scores across multiple API calls:
```python
result = await gabriel.rate(..., n_runs=3)
```

## GABRIEL Function Reference

| Function | Purpose | Output |
|----------|---------|--------|
| `extract()` | Pull structured facts from text | Strings/numbers |
| `rate()` | Score text on attributes | 0-100 scores |
| `classify()` | Assign text to categories | Label names |
| `whatever()` | Custom prompt analysis | Any format |
| `rank()` | Rank items by criteria | Rankings |
| `deduplicate()` | Find duplicate entries | Cluster IDs |
| `filter()` | Filter rows by criteria | Boolean mask |

### Modality Support

GABRIEL supports multiple input types via the `modality` parameter:

| Modality | Input Format |
|----------|-------------|
| `"text"` | Plain text (default) |
| `"image"` | Image file paths or URLs |
| `"audio"` | Audio file paths |
| `"web"` | Web URLs (auto-fetches content) |
| `"entity"` | Entity names for extraction |